= Getting started

Currently, there are no binary releases of `callme` available. That will change in the future, but in the meantime, you have to build it from source in order to use it. This document details the steps of doing that.

== What you need

=== Compiler

`callme` uses some C++14 features, and as such, requires a very recent compiler. The following compilers are tried and tested with `callme` at the moment:

  * g++ 5.0 
  * clang++ 3.7 
  * MSVC 2015 Update 1 

Newer versions of these compilers likely work, too.

TIP: This is not an exhaustive list; if you have success with other compilers, please let me know!

=== Tools

In addition to a capable compiler, you will need:

  * link:https://cmake.org[CMake 3.x]
  * GNU make (on *nixes) or MSBuild/Visual Studio (on Microsoft Windows).

=== Dependencies

`callme` has no external library dependencies, i.e. you don't need to install any extra libraries to use it. The library does use third-party code, but it is hidden both during compilation and linking (i.e. it means you don't need to worry about linking against those same libraries).

TIP: See the <<design.adoc#,Design>> documentation for details on how `callme` handles its dependencies.


== Building step by step

=== Unix-type systems

This includes most (all?) Linux distributions and cygwin. Building `callme` is very similar to other cmake-based projects:

[source]
----
git clone git@github.com:sztomi/callme.git
cd callme
mkdir build && cd build
cmake ..
make
----

And that's it. If all goes well, your build output will be in the lib, examples, and tests subfolders.

=== Microsoft Windows

On Windows with MSVC it is very similar, except you will probably want to 

TBD
[source]
----
git clone git@github.com:sztomi/callme.git
cd callme
mkdir build && cd build
cmake ..
make
----
