= Getting started
ifdef::env-github[:outfilesuffix: .adoc]

This document details the steps of getting everything in place to be able to use `callme`.

== What you need

=== Compiler

`callme` uses some C++14 features, and as such, requires a very recent compiler. The following compilers are tried and tested with `callme` at the moment:

  * g++ 5.0 
  * clang++ 3.7 
  * MSVC 2015 Update 1 

TIP: Newer versions of these compilers are expected to work.

=== Tools

In addition to a capable compiler, you will need:

  * link:https://cmake.org[CMake 3.x]
  * GNU make (on *nixes) or MSBuild/Visual Studio (on Microsoft Windows).

=== Dependencies

`callme` has no external library dependencies, i.e. you don't need to install any extra libraries to use it. The library does use third-party code, but it is hidden both during compilation and linking (i.e. it means you don't need to worry about linking against those same libraries).

TIP: See the <<design.adoc#,Design>> documentation for details on how `callme` handles its dependencies.


== Building 

`callme` uses CMake and has a very conventional build process. If you know how to build a CMake-based process, you know how to build `callme`.

If not, you can read the <<building.adoc#,Building>> chapter for step-by-step instructions. You can also visit that document for information on advanced building options.

